/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package starmap;

/**
 *
 * @author 7101020
 */
public class StarInfo extends javax.swing.JPanel {

    /**
     * Creates new form StarInfo
     */
    public StarInfo() {
        initComponents();
    }
    public void SetStarLabel(Star s)
    {
        jLabel1.setText(Integer.toString(s.hrNumber));
        
        if(s.name != null)
            jLabel2.setText(s.name);
        else
            jLabel2.setText("");
        
        if(s.commonName != null)
            jLabel3.setText(s.commonName);
        else
            jLabel3.setText("");
        
        if(s.constellation != null)
            jLabel4.setText(s.constellation);
        else
            jLabel4.setText("");
        
        if(s.starClass != null)
            jLabel5.setText(s.starClass);
        else
            jLabel5.setText("");
        
        jLabel6.setText(Double.toString(s.rightAscension));
        jLabel7.setText(Double.toString(s.declination));
        jLabel8.setText(Double.toString(s.magnitude));     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HRNumber = new javax.swing.JLabel();
        SName = new javax.swing.JLabel();
        Const = new javax.swing.JLabel();
        Ra = new javax.swing.JLabel();
        Dec = new javax.swing.JLabel();
        VMag = new javax.swing.JLabel();
        Class = new javax.swing.JLabel();
        CName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        HRNumber.setForeground(new java.awt.Color(255, 255, 255));
        HRNumber.setText("HRNumber:");

        SName.setForeground(new java.awt.Color(255, 255, 255));
        SName.setText("Star Name:");

        Const.setForeground(new java.awt.Color(255, 255, 255));
        Const.setText("Constellation:");

        Ra.setForeground(new java.awt.Color(255, 255, 255));
        Ra.setText("Ra: ");

        Dec.setForeground(new java.awt.Color(255, 255, 255));
        Dec.setText("Dec:");

        VMag.setForeground(new java.awt.Color(255, 255, 255));
        VMag.setText("VMag:");

        Class.setForeground(new java.awt.Color(255, 255, 255));
        Class.setText("Class:");

        CName.setForeground(new java.awt.Color(255, 255, 255));
        CName.setText("Common Name:");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("jLabel2");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("jLabel3");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("jLabel4");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("jLabel5");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("jLabel6");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("jLabel7");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CName)
                    .addComponent(HRNumber)
                    .addComponent(SName)
                    .addComponent(Const)
                    .addComponent(Class)
                    .addComponent(Ra)
                    .addComponent(Dec)
                    .addComponent(VMag))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HRNumber)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SName)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CName)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Const)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Class)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ra)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dec)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VMag)
                    .addComponent(jLabel8))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CName;
    private javax.swing.JLabel Class;
    private javax.swing.JLabel Const;
    private javax.swing.JLabel Dec;
    private javax.swing.JLabel HRNumber;
    private javax.swing.JLabel Ra;
    private javax.swing.JLabel SName;
    private javax.swing.JLabel VMag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
